---
- hosts: metric_source
  become: yes
  vars:
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.9.2-1.x86_64.rpm
  tasks:
    - name: "install htop"
      yum:
        name: htop
        state: present
    - name: "Install telegraf"
      yum:
        name: "{{ telegraf_url }}"
        state: present
    - name: "put cfg into path"
      copy:
        src: templates/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
    - name: "restart telegraf cfg"
      service:
        name: telegraf
        state: restarted

- hosts: metric_storage
  become: yes
  vars:
    influx_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.2.x86_64.rpm
  tasks:
    - name: "install influxdb"
      yum:
        name: "{{influx_url}}"
        state: present
    - name: "start influxdb"
      service:
        name: influxdb
        state: started
    
- hosts: metric_visualisation
  become: yes
  vars:
    grafana_url: https://dl.grafana.com/oss/release/grafana-5.4.3-1.x86_64.rpm 
  tasks:
    - yum:
        name: "{{grafana_url}}"
        state: present
    - service:
        name: "grafana-server"
        state: started